### ISSUE TITLE
Blocklists contain unrelated and duplicated lists

### ISSUE THREAD

**Issue by signed-log** [serverless-dns/blocklists#131]
Example :

https://github.com/serverless-dns/blocklists/blob/6cd8d55dffc03029ba4aedf79a082ebcc7eac81c/config.json#L740-L750

Infinitec has nothing to do bundled with the BlockList Project

#130 

I can do a cleanup of those entries, if you'd be interested

**Comment by ignoramous** [comment]
They both are scams and phishing lists? If so, that's why we may have bundled them up.

A separate entry is expensive as we have got only 256 slots of which 195 have been filled up... And also, a new entry (as opposed to agumenting an existing one) saved us a few MBs in the final compiled trie. And so, we don't create new entries unless the blocklist is uber popular (OISD, 1Hosts, EasyListnl, PeterLowe etc), or there is no other existing entry to which this blocklist could be attached to.
