### ISSUE TITLE
Add Olbat anti cryptojacking  list

### ISSUE THREAD

**Issue by trimechee** [serverless-dns/blocklists#160]
Hello, crypto mining is the most dangerous trhreat in the internet and it will be great to add olbat anti miners coin cryptojacking currency list to the lists of our beloved Rethink DNS, thank you so much :) 

https://raw.githubusercontent.com/olbat/ut1-blacklists/master/blacklists/cryptojacking/domains

and also : 

https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt

and

https://0xacab.org/my-privacy-dns/matrix/-/issues/new?issuable_template=CryptoMiner

**Comment by ignoramous** [comment]
*Thanks for your kind words (here and elsewhere). Appreciate it.* (:

I guess we should, as Olbat lists are generally of better quality.

**Comment by trimechee** [comment]
Great !! Thank you so much :)

**Comment by ignoramous** [comment]
Added Olbat's list: https://github.com/serverless-dns/blocklists/commit/64f14af2caf7e74819e9882617e97a9ecf2891c5

> https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt

That one's in `abp` format (which doesn't work that well with DNS based blockers) and doesn't look as exhaustive as other existing cryptojacking lists from zerodot1, hagezi, and the-blocklist-project.

> https://0xacab.org/my-privacy-dns/matrix/-/issues/new?issuable_template=CryptoMiner

I don't see a list here? We previously removed most MyPrivacyDNS lists because the server went offline for quite a bit: #107 

Closing this as complete, but feel free to reopen in any case.

**Comment by trimechee** [comment]
Instructive  ! thank you so much :) 💯
