### ISSUE TITLE
Include porn blocklist from "The Block List Project"

### ISSUE THREAD

**Issue by amithm7** [serverless-dns/blocklists#29]
A user says:
> I have another request, I use an app called draeneg to block porn , can it's lists be used , because rethink dns porn block is not sufficient
> https://github.com/blocklistproject/Lists
> That is where the block lists are

Possibly the list this user wants included: https://blocklistproject.github.io/Lists/porn.txt .

Some from "The Block List Project" were already included via #14 .

**Comment by amithm7** [comment]
some of them were removed here: 9b7c9d07811a90754412a651947c81759eb6b5e7

**Comment by ignoramous** [comment]
See also: #21

**Comment by ignoramous** [comment]
> @shuvashish76 some of them were removed here: https://github.com/serverless-dns/blocklists/commit/9b7c9d07811a90754412a651947c81759eb6b5e7

Removed because these lists have too many dead domains. Not only does this take up space but are incredibly wasteful to keep carrying forward along with other well-maintained lists.

If our analysis is off-the-mark, then please feel free to correct us, and we'd reconsider adding these back, after another round of evaluation.

**Comment by ignoramous** [comment]
https://github.com/serverless-dns/blocklists/blob/0face560fcf1012ce8e6a18d7e96a5b49ca816e9/config.json#L1508-L1514
